// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14/09/2025 07:15:37
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/wamp64/www/suivie-interventions/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/suivie-interventions/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/suivie-interventions/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/suivie-interventions/frontend/plugins/**/*.{js,ts,mjs}","C:/wamp64/www/suivie-interventions/frontend/composables/**/*.{js,ts,mjs}","C:/wamp64/www/suivie-interventions/frontend/utils/**/*.{js,ts,mjs}","C:/wamp64/www/suivie-interventions/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/suivie-interventions/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/suivie-interventions/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/suivie-interventions/frontend/app.config.{js,ts,mjs}","C:/wamp64/www/suivie-interventions/frontend/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;